
package cn.edu.nju.student_info;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T20:25:07.944+08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "学号错误", targetNamespace = "http://jw.nju.edu.cn/schema")
public class InvalidStudentId extends Exception {
    
    private java.lang.String 学号错误;

    public InvalidStudentId() {
        super();
    }
    
    public InvalidStudentId(String message) {
        super(message);
    }
    
    public InvalidStudentId(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidStudentId(String message, java.lang.String 学号错误) {
        super(message);
        this.学号错误 = 学号错误;
    }

    public InvalidStudentId(String message, java.lang.String 学号错误, Throwable cause) {
        super(message, cause);
        this.学号错误 = 学号错误;
    }

    public java.lang.String getFaultInfo() {
        return this.学号错误;
    }
}
