
package cn.edu.nju.student_info;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.parsers.FactoryConfigurationError;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

import cn.edu.nju.handlers.ClientHandlerResolver;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T20:25:07.890+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class StudentInfoService_StudentInfoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://jw.nju.edu.cn/wsdl", "StudentInfoServiceImplService");

    private StudentInfoService_StudentInfoServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StudentInfoServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        ObjectFactory factory = new ObjectFactory();
      
        StudentInfoServiceImplService ss = new StudentInfoServiceImplService(wsdlURL, SERVICE_NAME);
        
        
        ss.setHandlerResolver(new ClientHandlerResolver());
        
        StudentInfoService port = ss.getStudentInfoServicePort();  

//        {
//        System.out.println("Invoking addInfo...");
//        cn.edu.nju.student_info.学生信息 _addInfo_parametersVal = null;
//        javax.xml.ws.Holder<cn.edu.nju.student_info.学生信息> _addInfo_parameters = new javax.xml.ws.Holder<cn.edu.nju.student_info.学生信息>(_addInfo_parametersVal);
//        try {
//            port.addInfo(_addInfo_parameters);
//
//            System.out.println("addInfo._addInfo_parameters=" + _addInfo_parameters.value);
//        } catch (DataFormatError e) { 
//            System.out.println("Expected exception: DataFormatError has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking deleteInfo...");
//        cn.edu.nju.student_info.学号类型 _deleteInfo_parameters = factory.create学号类型();
//        _deleteInfo_parameters.set学号("141250162");
//        try {
//            cn.edu.nju.student_info.学生信息 _deleteInfo__return = port.deleteInfo(_deleteInfo_parameters);
//            System.out.println("deleteInfo.result=" + _deleteInfo__return);
//
//        } catch (InvalidStudentId e) { 
//            System.out.println("Expected exception: InvalidStudentId has occurred.");
//            System.out.println(e.toString());
//        }
//            }
        
        	
            cn.edu.nju.student_info.学生信息 _addInfo_parametersVal = factory.create学生信息();
            _addInfo_parametersVal.set学号("141250161");
            _addInfo_parametersVal.set年级("大三");
            
            	个人信息类型 personalInfo = factory.create个人信息类型();
            	personalInfo.set姓名("徐江河");
            	personalInfo.set婚姻状况("未婚");
            	personalInfo.set座机号码("1234567");
            	personalInfo.set性别("男");
            	personalInfo.set教育背景("本科");
            	personalInfo.set手机号码("15905190698");
            	
            	
            	课程成绩列表类型 scoreList = factory.create课程成绩列表类型();
//            	scoreList.get课程成绩().addAll(_queryInfo__return.课程成绩列表.get课程成绩());
          _addInfo_parametersVal.set基本信息(personalInfo);
          _addInfo_parametersVal.set课程成绩列表(scoreList);
    
        System.out.println("Invoking modifyInfo...");
        cn.edu.nju.student_info.学生信息 _modifyInfo_parametersVal = _addInfo_parametersVal;
        javax.xml.ws.Holder<cn.edu.nju.student_info.学生信息> _modifyInfo_parameters = new javax.xml.ws.Holder<cn.edu.nju.student_info.学生信息>(_modifyInfo_parametersVal);
        try {
            port.modifyInfo(_modifyInfo_parameters);

            System.out.println("modifyInfo._modifyInfo_parameters=" + _modifyInfo_parameters.value);
        } catch (DataFormatError e) { 
            System.out.println("Expected exception: DataFormatError has occurred.");
            System.out.println(e.toString());
        }
//            }
//      System.out.println("Invoking queryInfo...");
//      java.lang.String _queryInfo_parameters = "141250179";
//
//      cn.edu.nju.student_info.学生信息 _queryInfo__return = port.queryInfo(_queryInfo_parameters);
//
//      System.out.println("Invoking addInfo...");
//      ObjectFactory factory = new ObjectFactory();
//      

//      javax.xml.ws.Holder<cn.edu.nju.student_info.学生信息> _addInfo_parameters = new javax.xml.ws.Holder<cn.edu.nju.student_info.学生信息>(_addInfo_parametersVal);
//
//      port.addInfo(_addInfo_parameters);
//
//      String _queryInfo_parameters = "141250161";
//
//      cn.edu.nju.student_info.学生信息 _queryInfo__return = port.queryInfo(_queryInfo_parameters);
//      System.out.println(_queryInfo__return);
        System.exit(0);
    }

}
