
package cn.edu.nju.score_manage;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T20:05:40.256+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class ScoreManageService_ScoreManageServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://jw.nju.edu.cn/wsdl", "ScoreManageServiceImplService");

    private ScoreManageService_ScoreManageServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ScoreManageServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ScoreManageServiceImplService ss = new ScoreManageServiceImplService(wsdlURL, SERVICE_NAME);
        ScoreManageService port = ss.getScoreManageServicePort();  
        
        {
        System.out.println("Invoking deleteGrade...");
        cn.edu.nju.score_manage.学号课程号类型 _deleteGrade_parameters = null;
        try {
            cn.edu.nju.score_manage.课程成绩列表类型 _deleteGrade__return = port.deleteGrade(_deleteGrade_parameters);
            System.out.println("deleteGrade.result=" + _deleteGrade__return);

        } catch (InvalidCourseId e) { 
            System.out.println("Expected exception: InvalidCourseId has occurred.");
            System.out.println(e.toString());
        } catch (InvalidStudentId e) { 
            System.out.println("Expected exception: InvalidStudentId has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryGrade...");
        java.lang.String _queryGrade_parameters = "141250179";
        try {
            cn.edu.nju.score_manage.课程成绩列表类型 _queryGrade__return = port.queryGrade(_queryGrade_parameters);
            System.out.println("queryGrade.result=" + _queryGrade__return);

        } catch (InvalidStudentId e) { 
            System.out.println("Expected exception: InvalidStudentId has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking modifyGrade...");
        cn.edu.nju.score_manage.课程成绩类型 _modifyGrade_parameters = null;
        try {
            cn.edu.nju.score_manage.课程成绩列表类型 _modifyGrade__return = port.modifyGrade(_modifyGrade_parameters);
            System.out.println("modifyGrade.result=" + _modifyGrade__return);

        } catch (InvalidCourseId e) { 
            System.out.println("Expected exception: InvalidCourseId has occurred.");
            System.out.println(e.toString());
        } catch (InvalidStudentId e) { 
            System.out.println("Expected exception: InvalidStudentId has occurred.");
            System.out.println(e.toString());
        } catch (InvalidScore e) { 
            System.out.println("Expected exception: InvalidScore has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sortGrade...");
        cn.edu.nju.score_manage.排序类型 _sortGrade_parameters = null;
        try {
            cn.edu.nju.score_manage.课程成绩列表类型 _sortGrade__return = port.sortGrade(_sortGrade_parameters);
            System.out.println("sortGrade.result=" + _sortGrade__return);

        } catch (InvalidCourseId e) { 
            System.out.println("Expected exception: InvalidCourseId has occurred.");
            System.out.println(e.toString());
        } catch (InvalidStudentId e) { 
            System.out.println("Expected exception: InvalidStudentId has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addGrade...");
        cn.edu.nju.score_manage.课程成绩列表类型 _addGrade_parametersVal = null;
        javax.xml.ws.Holder<cn.edu.nju.score_manage.课程成绩列表类型> _addGrade_parameters = new javax.xml.ws.Holder<cn.edu.nju.score_manage.课程成绩列表类型>(_addGrade_parametersVal);
        try {
            port.addGrade(_addGrade_parameters);

            System.out.println("addGrade._addGrade_parameters=" + _addGrade_parameters.value);
        } catch (InvalidCourseId e) { 
            System.out.println("Expected exception: InvalidCourseId has occurred.");
            System.out.println(e.toString());
        } catch (InvalidStudentId e) { 
            System.out.println("Expected exception: InvalidStudentId has occurred.");
            System.out.println(e.toString());
        } catch (InvalidScore e) { 
            System.out.println("Expected exception: InvalidScore has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
