
package cn.edu.nju.login;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T22:24:41.786+08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "String", targetNamespace = "http://service.student.nju.edu/")
public class EmailPwdException extends Exception {
    
    private java.lang.String string;

    public EmailPwdException() {
        super();
    }
    
    public EmailPwdException(String message) {
        super(message);
    }
    
    public EmailPwdException(String message, Throwable cause) {
        super(message, cause);
    }

    public EmailPwdException(String message, java.lang.String string) {
        super(message);
        this.string = string;
    }

    public EmailPwdException(String message, java.lang.String string, Throwable cause) {
        super(message, cause);
        this.string = string;
    }

    public java.lang.String getFaultInfo() {
        return this.string;
    }
}
