
package cn.edu.nju.login;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T22:24:41.731+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class UserService_UserServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.student.nju.edu/", "UserService");

    private UserService_UserServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserService_Service ss = new UserService_Service(wsdlURL, SERVICE_NAME);
        UserService port = ss.getUserServiceImplPort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_email = "";
        java.lang.String _login_password = "";
        try {
            cn.edu.nju.login.UserEntity _login__return = port.login(_login_email, _login_password);
            System.out.println("login.result=" + _login__return);

        } catch (ParamNullException e) { 
            System.out.println("Expected exception: ParamNullException has occurred.");
            System.out.println(e.toString());
        } catch (EmailPwdException e) { 
            System.out.println("Expected exception: EmailPwdException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
